### ISSUE TITLE
Missing the minlength argument

### ISSUE THREAD

**Issue by thedatadudech** [zero-to-mastery/complete-web-developer-manual#91] opened 2023-09-02 22:29 UTC
I am currently enrolled in your course on becoming a complete web developer, as God wills. I noticed in one of your instructional videos that you mistakenly used the 'min' attribute for password validation, when you actually intended to use 'minlength.' I also observed that the 'min' attribute is still present in the markup code here, maybe you also want to mention 'minlength' here, and as god wishes, would like to create my first pull request here with you

**Comment by Mansvini** [comment] 2024-04-18 16:22
Fixed this with PR #95

**Comment by l-white** [comment] 2024-10-29 17:11
Closing the request as the issue is now resolved

**Closed by l-white** 2024-10-29 17:11 UTC
